name: NPM Publish

on:
  push:
    branches:
      - experimental
    tags:
      - v*.*.*
      - v*.*.*-*

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: true
      - id: get_version
        uses: actions/github-script@v5
        with:
          script: |
            const sha = context.sha.substring(0, 7)
            const branchName = context.ref.startsWith('refs/heads/') ? context.ref.substring('refs/heads/'.length) : ''
            const version = branchName ? `0.0.0-${branchName}.${sha}` : context.ref.substring('refs/tags/v'.length)
            const tag = branchName ? branchName : version.match(/^\d+\.\d+\.\d+$/) ? 'latest' : version.match(/^\d+\.\d+\.\d+-([\d\w]+)/)[1]
            core.setOutput('version', version)
            core.setOutput('tag', tag)
      - name: Build
        run: pnpm build
      - name: version
        run: pnpm build:version -- ${{ steps.get_version.outputs.version }}

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ steps.get_version.outputs.tag }}
          package: ./dist/core/package.json
          access: public
